	;Miramos en que estado estamos
	;Acabamos de empezar?
	PAGESELW	POR_;
	MOVF	MAQUINA_EST,W;
	XORLW	POR;
	BTFSC	STATUS,Z;
		CALL	POR_;
	;Estamos en reposo?
	PAGESELW	STANDBY_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	STANDBY;
	BTFSC	STATUS,Z;
		CALL	STANDBY_;
	;Estamos en el "escritorio"
	PAGESELW	UNLOCK_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	UNLOCK;
	BTFSC	STATUS,Z;
		CALL	UNLOCK_;
	;Estamos marcando un número?
	PAGESELW	MARCA_
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MARCA;
	BTFSC	STATUS,Z;
		CALL	MARCA_;
	;Estamos en el menú principal?
	PAGESELW	MENU12_1_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MENU12_1;
	BTFSC	STATUS,Z;
		CALL	MENU12_1_;
	;Estamos dentro del menú de mensajes, en el indice 1?
	PAGESELW	MENSAJES_1_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MENSAJES_1;
	BTFSC	STATUS,Z;
		CALL	MENSAJES_1_;
	;Estamos dentro del menú de mensajes, en el indice 2?
	PAGESELW	MENSAJES_2_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MENSAJES_2;
	BTFSC	STATUS,Z;
		CALL	MENSAJES_2_;
	;Estamos en el menu para leer sms?
	PAGESELW	LEER_SMS_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	LEER_SMS;
	BTFSC	STATUS,Z;
		CALL	LEER_SMS_;
	;Estamos escribiendo un sms?
	PAGESELW	ESCRIBIR_SMS_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	ESCRIBIR_SMS;
	BTFSC	STATUS,Z;
		CALL	ESCRIBIR_SMS_;