	;Miramos en que estado estamos
	;Acabamos de empezar?
	PAGESELW	POR_;
	MOVF	MAQUINA_EST,W;
	XORLW	POR;
	BTFSC	STATUS,Z;
		CALL	POR_;
	;Estamos en reposo?
	PAGESELW	STANDBY_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	STANDBY;
	BTFSC	STATUS,Z;
		CALL	STANDBY_;
	;Estamos en el "escritorio"
	PAGESELW	UNLOCK_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	UNLOCK;
	BTFSC	STATUS,Z;
		CALL	UNLOCK_;
	;Estamos en el menú principal?
	PAGESELW	MENU12_1_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MENU12_1;
	BTFSC	STATUS,Z;
		CALL	MENU12_1_;
	;Estamos escribiendo un sms?
	PAGESELW	ESCRIBIR_SMS_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	ESCRIBIR_SMS;
	BTFSC	STATUS,Z;
		CALL	ESCRIBIR_SMS_;
	PAGESELW	MANDAR_SMS_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	MANDAR_SMS;
	BTFSC	STATUS,Z;
		CALL	MANDAR_SMS_;
	PAGESELW	ENVIAR_SMS_;
	CLRF	STATUS;
	MOVF	MAQUINA_EST,W;
	XORLW	ENVIAR_SMS;
	BTFSC	STATUS,Z;
		CALL	ENVIAR_SMS_;