% Signal Processing and Communications Toolbox
% SSPI software interface functions.
% Version 2.00, 4/30/94
% LT Dennis W. Brown
% Naval Postgraduate School
% Monterey, CA
%
% SSPI software "front-ends."
%   SSPIPAM     SSPI 'sxaf' program front-end.
%   SSPISXAF    SSPI 'sxaf' program front-end.
%
% SSPI data file functions.
%   LOADSURF    Load surface generated by 'sxaf' SSPI program.
%   LOADSSPI    Loads SSPI software generated data files.
%   SAVESSPI    Saves a vector to SSPI formatted files.

