package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Assistances;
import org.lmb97.data.AssistancesExample;

public interface AssistancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(AssistancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(AssistancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(Assistances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(Assistances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<Assistances> selectByExample(AssistancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    Assistances selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Assistances record, @Param("example") AssistancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") Assistances record, @Param("example") AssistancesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(Assistances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assistances
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(Assistances record);
}