package org.lmb97.data;

import java.util.Date;

public class Assistances {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assistances.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assistances.person
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Integer person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assistances.arrival
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Date arrival;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assistances.event
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Integer event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assistances.reason
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Integer reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assistances.id
     *
     * @return the value of assistances.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assistances.id
     *
     * @param id the value for assistances.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assistances.person
     *
     * @return the value of assistances.person
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assistances.person
     *
     * @param person the value for assistances.person
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setPerson(Integer person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assistances.arrival
     *
     * @return the value of assistances.arrival
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Date getArrival() {
        return arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assistances.arrival
     *
     * @param arrival the value for assistances.arrival
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setArrival(Date arrival) {
        this.arrival = arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assistances.event
     *
     * @return the value of assistances.event
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Integer getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assistances.event
     *
     * @param event the value for assistances.event
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setEvent(Integer event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assistances.reason
     *
     * @return the value of assistances.reason
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Integer getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assistances.reason
     *
     * @param reason the value for assistances.reason
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setReason(Integer reason) {
        this.reason = reason;
    }
}