package org.lmb97.data;

public class Authors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.author
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authors.style
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private String style;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.id
     *
     * @return the value of authors.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.id
     *
     * @param id the value for authors.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.author
     *
     * @return the value of authors.author
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.author
     *
     * @param author the value for authors.author
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authors.style
     *
     * @return the value of authors.style
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authors.style
     *
     * @param style the value for authors.style
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }
}