package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Authors;
import org.lmb97.data.AuthorsExample;

public interface AuthorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int countByExample(AuthorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int deleteByExample(AuthorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int insert(Authors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int insertSelective(Authors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    List<Authors> selectByExample(AuthorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    Authors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Authors record, @Param("example") AuthorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByExample(@Param("record") Authors record, @Param("example") AuthorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByPrimaryKeySelective(Authors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authors
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByPrimaryKey(Authors record);
}