package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.EventTypes;
import org.lmb97.data.EventTypesExample;

public interface EventTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(EventTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(EventTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(EventTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(EventTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<EventTypes> selectByExample(EventTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    EventTypes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") EventTypes record, @Param("example") EventTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") EventTypes record, @Param("example") EventTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(EventTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_types
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(EventTypes record);
}