package org.lmb97.data;

public class EventTypes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_types.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_types.name
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_types.post
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer post;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_types.id
     *
     * @return the value of event_types.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_types.id
     *
     * @param id the value for event_types.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_types.name
     *
     * @return the value of event_types.name
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_types.name
     *
     * @param name the value for event_types.name
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_types.post
     *
     * @return the value of event_types.post
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_types.post
     *
     * @param post the value for event_types.post
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setPost(Integer post) {
        this.post = post;
    }
}