package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Events;
import org.lmb97.data.EventsExample;

public interface EventsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<Events> selectByExample(EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    Events selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Events record, @Param("example") EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") Events record, @Param("example") EventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(Events record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(Events record);
}