package org.lmb97.data;

import java.util.Date;

public class Events {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.event_type
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column events.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer season;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.id
     *
     * @return the value of events.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.id
     *
     * @param id the value for events.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.date
     *
     * @return the value of events.date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.date
     *
     * @param date the value for events.date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.event_type
     *
     * @return the value of events.event_type
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.event_type
     *
     * @param eventType the value for events.event_type
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column events.season
     *
     * @return the value of events.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column events.season
     *
     * @param season the value for events.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setSeason(Integer season) {
        this.season = season;
    }
}