package org.lmb97.data;

public class Files {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.file
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private String file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.id
     *
     * @return the value of files.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.id
     *
     * @param id the value for files.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.file
     *
     * @return the value of files.file
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.file
     *
     * @param file the value for files.file
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }
}