package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Files;
import org.lmb97.data.FilesExample;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int countByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    List<Files> selectByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    Files selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExample(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByPrimaryKey(Files record);
}