package org.lmb97.data;

public class Instruments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruments.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instruments.name
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruments.id
     *
     * @return the value of instruments.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruments.id
     *
     * @param id the value for instruments.id
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instruments.name
     *
     * @return the value of instruments.name
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instruments.name
     *
     * @param name the value for instruments.name
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}