package org.lmb97.data;

public class Lottery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.total_lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer totalLottery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery.series
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer series;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.id
     *
     * @return the value of lottery.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.id
     *
     * @param id the value for lottery.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.total_lottery
     *
     * @return the value of lottery.total_lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getTotalLottery() {
        return totalLottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.total_lottery
     *
     * @param totalLottery the value for lottery.total_lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setTotalLottery(Integer totalLottery) {
        this.totalLottery = totalLottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.number
     *
     * @return the value of lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.number
     *
     * @param number the value for lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery.series
     *
     * @return the value of lottery.series
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getSeries() {
        return series;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery.series
     *
     * @param series the value for lottery.series
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setSeries(Integer series) {
        this.series = series;
    }
}