package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Lottery;
import org.lmb97.data.LotteryExample;

public interface LotteryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int countByExample(LotteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByExample(LotteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insert(Lottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insertSelective(Lottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    List<Lottery> selectByExample(LotteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    Lottery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Lottery record, @Param("example") LotteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExample(@Param("record") Lottery record, @Param("example") LotteryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByPrimaryKeySelective(Lottery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByPrimaryKey(Lottery record);
}