package org.lmb97.data;

import java.util.Date;

public class Musicsheets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.title
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.author
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.acquisitor
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer acquisitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.acquisition_date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Date acquisitionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicsheets.provider
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer provider;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.id
     *
     * @return the value of musicsheets.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.id
     *
     * @param id the value for musicsheets.id
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.title
     *
     * @return the value of musicsheets.title
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.title
     *
     * @param title the value for musicsheets.title
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.author
     *
     * @return the value of musicsheets.author
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.author
     *
     * @param author the value for musicsheets.author
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.acquisitor
     *
     * @return the value of musicsheets.acquisitor
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getAcquisitor() {
        return acquisitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.acquisitor
     *
     * @param acquisitor the value for musicsheets.acquisitor
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setAcquisitor(Integer acquisitor) {
        this.acquisitor = acquisitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.acquisition_date
     *
     * @return the value of musicsheets.acquisition_date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Date getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.acquisition_date
     *
     * @param acquisitionDate the value for musicsheets.acquisition_date
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setAcquisitionDate(Date acquisitionDate) {
        this.acquisitionDate = acquisitionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicsheets.provider
     *
     * @return the value of musicsheets.provider
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicsheets.provider
     *
     * @param provider the value for musicsheets.provider
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setProvider(Integer provider) {
        this.provider = provider;
    }
}