package org.lmb97.data;

import java.util.Date;

public class People {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.name
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.surname
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String surname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.birth
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.phone_mobile
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer phoneMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.dni_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer dniNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.dni_letter
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String dniLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.phone_house
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer phoneHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.address
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.postcode
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.join_ref
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer joinRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.password
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.nick
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private String nick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.id
     *
     * @return the value of people.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.id
     *
     * @param id the value for people.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.name
     *
     * @return the value of people.name
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.name
     *
     * @param name the value for people.name
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.surname
     *
     * @return the value of people.surname
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.surname
     *
     * @param surname the value for people.surname
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setSurname(String surname) {
        this.surname = surname == null ? null : surname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.birth
     *
     * @return the value of people.birth
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.birth
     *
     * @param birth the value for people.birth
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.phone_mobile
     *
     * @return the value of people.phone_mobile
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPhoneMobile() {
        return phoneMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.phone_mobile
     *
     * @param phoneMobile the value for people.phone_mobile
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPhoneMobile(Integer phoneMobile) {
        this.phoneMobile = phoneMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.dni_number
     *
     * @return the value of people.dni_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getDniNumber() {
        return dniNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.dni_number
     *
     * @param dniNumber the value for people.dni_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setDniNumber(Integer dniNumber) {
        this.dniNumber = dniNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.dni_letter
     *
     * @return the value of people.dni_letter
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getDniLetter() {
        return dniLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.dni_letter
     *
     * @param dniLetter the value for people.dni_letter
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setDniLetter(String dniLetter) {
        this.dniLetter = dniLetter == null ? null : dniLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.phone_house
     *
     * @return the value of people.phone_house
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPhoneHouse() {
        return phoneHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.phone_house
     *
     * @param phoneHouse the value for people.phone_house
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPhoneHouse(Integer phoneHouse) {
        this.phoneHouse = phoneHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.address
     *
     * @return the value of people.address
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.address
     *
     * @param address the value for people.address
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.postcode
     *
     * @return the value of people.postcode
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.postcode
     *
     * @param postcode the value for people.postcode
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPostcode(Integer postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.join_ref
     *
     * @return the value of people.join_ref
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getJoinRef() {
        return joinRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.join_ref
     *
     * @param joinRef the value for people.join_ref
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setJoinRef(Integer joinRef) {
        this.joinRef = joinRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.password
     *
     * @return the value of people.password
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.password
     *
     * @param password the value for people.password
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.nick
     *
     * @return the value of people.nick
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.nick
     *
     * @param nick the value for people.nick
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }
}