package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Posts;
import org.lmb97.data.PostsExample;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<Posts> selectByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    Posts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(Posts record);
}