package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Providers;
import org.lmb97.data.ProvidersExample;

public interface ProvidersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(ProvidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(ProvidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(Providers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(Providers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<Providers> selectByExample(ProvidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    Providers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Providers record, @Param("example") ProvidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") Providers record, @Param("example") ProvidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(Providers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table providers
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(Providers record);
}