package org.lmb97.data;

public class Providers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column providers.provider
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    private String provider;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.id
     *
     * @return the value of providers.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.id
     *
     * @param id the value for providers.id
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column providers.provider
     *
     * @return the value of providers.provider
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column providers.provider
     *
     * @param provider the value for providers.provider
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }
}