package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Reasons;
import org.lmb97.data.ReasonsExample;

public interface ReasonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(ReasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(ReasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(Reasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(Reasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<Reasons> selectByExample(ReasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    Reasons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Reasons record, @Param("example") ReasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") Reasons record, @Param("example") ReasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(Reasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reasons
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(Reasons record);
}