package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.RelMusicsheetsInstruments;
import org.lmb97.data.RelMusicsheetsInstrumentsExample;
import org.lmb97.data.RelMusicsheetsInstrumentsKey;

public interface RelMusicsheetsInstrumentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int countByExample(RelMusicsheetsInstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByExample(RelMusicsheetsInstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int deleteByPrimaryKey(RelMusicsheetsInstrumentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insert(RelMusicsheetsInstruments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int insertSelective(RelMusicsheetsInstruments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    List<RelMusicsheetsInstruments> selectByExample(RelMusicsheetsInstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    RelMusicsheetsInstruments selectByPrimaryKey(RelMusicsheetsInstrumentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExampleSelective(@Param("record") RelMusicsheetsInstruments record, @Param("example") RelMusicsheetsInstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByExample(@Param("record") RelMusicsheetsInstruments record, @Param("example") RelMusicsheetsInstrumentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKeySelective(RelMusicsheetsInstruments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_instruments
     *
     * @mbggenerated Tue Apr 24 07:34:33 CEST 2012
     */
    int updateByPrimaryKey(RelMusicsheetsInstruments record);
}