package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.RelMusicsheetsEventsExample;
import org.lmb97.data.RelMusicsheetsEventsKey;

public interface RelMusicsheetsEventsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int countByExample(RelMusicsheetsEventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByExample(RelMusicsheetsEventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByPrimaryKey(RelMusicsheetsEventsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insert(RelMusicsheetsEventsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insertSelective(RelMusicsheetsEventsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    List<RelMusicsheetsEventsKey> selectByExample(RelMusicsheetsEventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExampleSelective(@Param("record") RelMusicsheetsEventsKey record, @Param("example") RelMusicsheetsEventsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExample(@Param("record") RelMusicsheetsEventsKey record, @Param("example") RelMusicsheetsEventsExample example);
}