package org.lmb97.data;

public class RelMusicsheetsInstruments extends RelMusicsheetsInstrumentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_instruments.file
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_instruments.voices_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Byte voicesNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_instruments.file
     *
     * @return the value of rel_musicsheets_instruments.file
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_instruments.file
     *
     * @param file the value for rel_musicsheets_instruments.file
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setFile(Integer file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_instruments.voices_number
     *
     * @return the value of rel_musicsheets_instruments.voices_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Byte getVoicesNumber() {
        return voicesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_instruments.voices_number
     *
     * @param voicesNumber the value for rel_musicsheets_instruments.voices_number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setVoicesNumber(Byte voicesNumber) {
        this.voicesNumber = voicesNumber;
    }
}