package org.lmb97.data;

public class RelMusicsheetsInstrumentsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_instruments.instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_instruments.musicsheet
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer musicsheet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_instruments.instrument
     *
     * @return the value of rel_musicsheets_instruments.instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_instruments.instrument
     *
     * @param instrument the value for rel_musicsheets_instruments.instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setInstrument(Integer instrument) {
        this.instrument = instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_instruments.musicsheet
     *
     * @return the value of rel_musicsheets_instruments.musicsheet
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getMusicsheet() {
        return musicsheet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_instruments.musicsheet
     *
     * @param musicsheet the value for rel_musicsheets_instruments.musicsheet
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setMusicsheet(Integer musicsheet) {
        this.musicsheet = musicsheet;
    }
}