package org.lmb97.data;

public class RelMusicsheetsEventsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_events.event
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer event;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_musicsheets_events.musicsheet
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer musicsheet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_events.event
     *
     * @return the value of rel_musicsheets_events.event
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_events.event
     *
     * @param event the value for rel_musicsheets_events.event
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setEvent(Integer event) {
        this.event = event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_musicsheets_events.musicsheet
     *
     * @return the value of rel_musicsheets_events.musicsheet
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getMusicsheet() {
        return musicsheet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_musicsheets_events.musicsheet
     *
     * @param musicsheet the value for rel_musicsheets_events.musicsheet
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setMusicsheet(Integer musicsheet) {
        this.musicsheet = musicsheet;
    }
}