package org.lmb97.data;

import java.util.ArrayList;
import java.util.List;

public class RelMusicsheetsEventsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public RelMusicsheetsEventsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEventIsNull() {
            addCriterion("event is null");
            return (Criteria) this;
        }

        public Criteria andEventIsNotNull() {
            addCriterion("event is not null");
            return (Criteria) this;
        }

        public Criteria andEventEqualTo(Integer value) {
            addCriterion("event =", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotEqualTo(Integer value) {
            addCriterion("event <>", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventGreaterThan(Integer value) {
            addCriterion("event >", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventGreaterThanOrEqualTo(Integer value) {
            addCriterion("event >=", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventLessThan(Integer value) {
            addCriterion("event <", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventLessThanOrEqualTo(Integer value) {
            addCriterion("event <=", value, "event");
            return (Criteria) this;
        }

        public Criteria andEventIn(List<Integer> values) {
            addCriterion("event in", values, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotIn(List<Integer> values) {
            addCriterion("event not in", values, "event");
            return (Criteria) this;
        }

        public Criteria andEventBetween(Integer value1, Integer value2) {
            addCriterion("event between", value1, value2, "event");
            return (Criteria) this;
        }

        public Criteria andEventNotBetween(Integer value1, Integer value2) {
            addCriterion("event not between", value1, value2, "event");
            return (Criteria) this;
        }

        public Criteria andMusicsheetIsNull() {
            addCriterion("musicsheet is null");
            return (Criteria) this;
        }

        public Criteria andMusicsheetIsNotNull() {
            addCriterion("musicsheet is not null");
            return (Criteria) this;
        }

        public Criteria andMusicsheetEqualTo(Integer value) {
            addCriterion("musicsheet =", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetNotEqualTo(Integer value) {
            addCriterion("musicsheet <>", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetGreaterThan(Integer value) {
            addCriterion("musicsheet >", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetGreaterThanOrEqualTo(Integer value) {
            addCriterion("musicsheet >=", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetLessThan(Integer value) {
            addCriterion("musicsheet <", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetLessThanOrEqualTo(Integer value) {
            addCriterion("musicsheet <=", value, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetIn(List<Integer> values) {
            addCriterion("musicsheet in", values, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetNotIn(List<Integer> values) {
            addCriterion("musicsheet not in", values, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetBetween(Integer value1, Integer value2) {
            addCriterion("musicsheet between", value1, value2, "musicsheet");
            return (Criteria) this;
        }

        public Criteria andMusicsheetNotBetween(Integer value1, Integer value2) {
            addCriterion("musicsheet not between", value1, value2, "musicsheet");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 17 19:12:25 CEST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_musicsheets_events
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}