package org.lmb97.data;

public class RelPeopleLotteryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_lottery.lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer lottery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_lottery.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_lottery.lottery
     *
     * @return the value of rel_people_lottery.lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getLottery() {
        return lottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_lottery.lottery
     *
     * @param lottery the value for rel_people_lottery.lottery
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setLottery(Integer lottery) {
        this.lottery = lottery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_lottery.number
     *
     * @return the value of rel_people_lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_lottery.number
     *
     * @param number the value for rel_people_lottery.number
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_lottery.person
     *
     * @return the value of rel_people_lottery.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_lottery.person
     *
     * @param person the value for rel_people_lottery.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPerson(Integer person) {
        this.person = person;
    }
}