package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.RelPeopleEmailsExample;
import org.lmb97.data.RelPeopleEmailsKey;

public interface RelPeopleEmailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int countByExample(RelPeopleEmailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByExample(RelPeopleEmailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int deleteByPrimaryKey(RelPeopleEmailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insert(RelPeopleEmailsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int insertSelective(RelPeopleEmailsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    List<RelPeopleEmailsKey> selectByExample(RelPeopleEmailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExampleSelective(@Param("record") RelPeopleEmailsKey record, @Param("example") RelPeopleEmailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_people_emails
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    int updateByExample(@Param("record") RelPeopleEmailsKey record, @Param("example") RelPeopleEmailsExample example);
}