package org.lmb97.data;

public class RelPeopleLottery extends RelPeopleLotteryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_lottery.sold
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer sold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_lottery.sold
     *
     * @return the value of rel_people_lottery.sold
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_lottery.sold
     *
     * @param sold the value for rel_people_lottery.sold
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setSold(Integer sold) {
        this.sold = sold;
    }
}