package org.lmb97.data;

public class RelPeopleInstruments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_instruments.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_instruments.instrument
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer instrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_instruments.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_instruments.id
     *
     * @return the value of rel_people_instruments.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_instruments.id
     *
     * @param id the value for rel_people_instruments.id
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_instruments.instrument
     *
     * @return the value of rel_people_instruments.instrument
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_instruments.instrument
     *
     * @param instrument the value for rel_people_instruments.instrument
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setInstrument(Integer instrument) {
        this.instrument = instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_instruments.person
     *
     * @return the value of rel_people_instruments.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_instruments.person
     *
     * @param person the value for rel_people_instruments.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPerson(Integer person) {
        this.person = person;
    }
}