package org.lmb97.data;

import java.util.Date;

public class RelPostsPeopleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_posts_people.join_date
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_posts_people.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_posts_people.post
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    private Integer post;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_posts_people.join_date
     *
     * @return the value of rel_posts_people.join_date
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_posts_people.join_date
     *
     * @param joinDate the value for rel_posts_people.join_date
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_posts_people.person
     *
     * @return the value of rel_posts_people.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_posts_people.person
     *
     * @param person the value for rel_posts_people.person
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPerson(Integer person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_posts_people.post
     *
     * @return the value of rel_posts_people.post
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public Integer getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_posts_people.post
     *
     * @param post the value for rel_posts_people.post
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    public void setPost(Integer post) {
        this.post = post;
    }
}