package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.RelPostsPeople;
import org.lmb97.data.RelPostsPeopleExample;
import org.lmb97.data.RelPostsPeopleKey;

public interface RelPostsPeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int countByExample(RelPostsPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int deleteByExample(RelPostsPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int deleteByPrimaryKey(RelPostsPeopleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int insert(RelPostsPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int insertSelective(RelPostsPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    List<RelPostsPeople> selectByExample(RelPostsPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    RelPostsPeople selectByPrimaryKey(RelPostsPeopleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByExampleSelective(@Param("record") RelPostsPeople record, @Param("example") RelPostsPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByExample(@Param("record") RelPostsPeople record, @Param("example") RelPostsPeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByPrimaryKeySelective(RelPostsPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_posts_people
     *
     * @mbggenerated Tue May 15 11:58:16 CEST 2012
     */
    int updateByPrimaryKey(RelPostsPeople record);
}