package org.lmb97.data;

public class RelPeopleEmailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_emails.email
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_people_emails.person
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer person;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_emails.email
     *
     * @return the value of rel_people_emails.email
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_emails.email
     *
     * @param email the value for rel_people_emails.email
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setEmail(Integer email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_people_emails.person
     *
     * @return the value of rel_people_emails.person
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_people_emails.person
     *
     * @param person the value for rel_people_emails.person
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setPerson(Integer person) {
        this.person = person;
    }
}