package org.lmb97.data;

import java.util.Date;

public class RelPostsPeople extends RelPostsPeopleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_posts_people.out_date
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    private Date outDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_posts_people.out_date
     *
     * @return the value of rel_posts_people.out_date
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_posts_people.out_date
     *
     * @param outDate the value for rel_posts_people.out_date
     *
     * @mbggenerated Sun Apr 29 01:20:10 CEST 2012
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }
}