package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.RelRelPeopleInstrumentsSeasonsExample;
import org.lmb97.data.RelRelPeopleInstrumentsSeasonsKey;

public interface RelRelPeopleInstrumentsSeasonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int countByExample(RelRelPeopleInstrumentsSeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByExample(RelRelPeopleInstrumentsSeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByPrimaryKey(RelRelPeopleInstrumentsSeasonsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insert(RelRelPeopleInstrumentsSeasonsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insertSelective(RelRelPeopleInstrumentsSeasonsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    List<RelRelPeopleInstrumentsSeasonsKey> selectByExample(RelRelPeopleInstrumentsSeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExampleSelective(@Param("record") RelRelPeopleInstrumentsSeasonsKey record, @Param("example") RelRelPeopleInstrumentsSeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel__rel_people_instruments__seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExample(@Param("record") RelRelPeopleInstrumentsSeasonsKey record, @Param("example") RelRelPeopleInstrumentsSeasonsExample example);
}