package org.lmb97.data;

public class RelRelPeopleInstrumentsSeasonsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel__rel_people_instruments__seasons.person_instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer personInstrument;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel__rel_people_instruments__seasons.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    private Integer season;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel__rel_people_instruments__seasons.person_instrument
     *
     * @return the value of rel__rel_people_instruments__seasons.person_instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getPersonInstrument() {
        return personInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel__rel_people_instruments__seasons.person_instrument
     *
     * @param personInstrument the value for rel__rel_people_instruments__seasons.person_instrument
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setPersonInstrument(Integer personInstrument) {
        this.personInstrument = personInstrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel__rel_people_instruments__seasons.season
     *
     * @return the value of rel__rel_people_instruments__seasons.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public Integer getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel__rel_people_instruments__seasons.season
     *
     * @param season the value for rel__rel_people_instruments__seasons.season
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    public void setSeason(Integer season) {
        this.season = season;
    }
}