package org.lmb97.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lmb97.data.Seasons;
import org.lmb97.data.SeasonsExample;

public interface SeasonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int countByExample(SeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByExample(SeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insert(Seasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int insertSelective(Seasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    List<Seasons> selectByExample(SeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    Seasons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExampleSelective(@Param("record") Seasons record, @Param("example") SeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByExample(@Param("record") Seasons record, @Param("example") SeasonsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByPrimaryKeySelective(Seasons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seasons
     *
     * @mbggenerated Tue Apr 17 19:12:25 CEST 2012
     */
    int updateByPrimaryKey(Seasons record);
}